cmake_minimum_required(VERSION 3.13)
set(PICO_BOARD pico2)
include(${PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(usb_probe C CXX ASM)
pico_sdk_init()
add_executable(usb_probe main.c)
target_link_libraries(usb_probe pico_stdlib)
pico_enable_stdio_usb(usb_probe 1)
pico_enable_stdio_uart(usb_probe 0)
pico_add_extra_outputs(usb_probe)
